robot_state_publisher:
  ros__parameters:
    publish_frequency: 60.0

joint_state_publisher:
  ros__parameters:
    rate: 60.0
    zeros:
      left_hip_pitch_joint: 0.4
      left_hip_roll_joint: 0.05
      left_hip_yaw_joint: -0.31
      left_knee_pitch_joint: 0.49
      left_ankle_pitch_joint: -0.21
      left_ankle_roll_joint: -0.0
      right_hip_pitch_joint: -0.4
      right_hip_roll_joint: -0.05
      right_hip_yaw_joint: 0.31
      right_knee_pitch_joint: 0.49
      right_ankle_pitch_joint: -0.21
      right_ankle_roll_joint: 0.0
